name: Sync Fork AIOLists

on:
  schedule:
    - cron: '0 4 * * *' # Varje dag kl 04:00 svensk tid
  workflow_dispatch: # Möjlighet att köra manuellt

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/SebastianMorel/AIOLists.git
          git fetch upstream

      - name: Merge Changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories || true

      - name: Push Changes
        run: |
          git push origin main
